baseURL = "/"
contentDir = "content"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
languageCode = "zh-cn"
theme = "docsy"
title = "FiveM & RedM 中文网"
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "monokai"

disablePathToLower = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML"]

[params]
copyright = "FiveM & RedM 中文网"
disableHomeIcon = true
editURL = "https://github.com/malagebe/fivem-docs-cn/edit/master/content/"
github_branch = "master"
github_project_repo = "https://github.com/citizenfx/fivem"
github_repo = "https://github.com/malagebe/fivem-docs-cn"
offlineSearch = true
time_format_blog = "2006年01月02日"
time_format_default = "2006年01月02日"

[blackfriday]
hrefTargetBlank = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "首页"
url = "/"
weight = 10

[[menu.main]]
name = "中文社区"
url = "https://forum.fivem.net.cn"
weight = 20

[[menu.main]]
name = "服务器"
url = "/docs/support/servers/"
weight = 40

[[menu.main]]
name = "GitHub"
url = "https://github.com/citizenfx/fivem"
weight = 50

[[menu.main]]
name = "RedM中文网"
url = "/redm/"
weight = 70

[params.ui]
sidebar_menu_compact = true
